// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using physiocare_backend.Data;

#nullable disable

namespace physiocare_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519201411_MigracionInicialProyecto")]
    partial class MigracionInicialProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("physiocare_backend.Models.CategoriaTerapia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("CategoriasTerapias");

                    b.HasData(
                        new
                        {
                            id = 1,
                            EspecialidadId = 1,
                            nombre = "Fisioterapia Preventiva (Pre-Lesión)"
                        },
                        new
                        {
                            id = 2,
                            EspecialidadId = 1,
                            nombre = "Fisioterapia de Campo"
                        },
                        new
                        {
                            id = 3,
                            EspecialidadId = 1,
                            nombre = "Fisioterapia de Recuperación (Post-Esfuerzo)"
                        },
                        new
                        {
                            id = 4,
                            EspecialidadId = 2,
                            nombre = "Fisioterapia para el Envejicimiento Activo (Preventiva)"
                        },
                        new
                        {
                            id = 5,
                            EspecialidadId = 2,
                            nombre = "Fisioterapia Neurológica Geriátrica"
                        },
                        new
                        {
                            id = 6,
                            EspecialidadId = 2,
                            nombre = "Fisioterapia en Cuidados Paliativos"
                        },
                        new
                        {
                            id = 7,
                            EspecialidadId = 3,
                            nombre = "Fisioterapia en Insuficiencia Cardíaca Crónica"
                        },
                        new
                        {
                            id = 8,
                            EspecialidadId = 3,
                            nombre = "Fisioterapia Vascular Periférica"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.Cita", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("EstadoCitaId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioTerapiaId")
                        .HasColumnType("int");

                    b.Property<int>("TerapeutaId")
                        .HasColumnType("int");

                    b.Property<int>("duracionEstimada")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("horaInicio")
                        .HasColumnType("time");

                    b.Property<string>("notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("EstadoCitaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ServicioTerapiaId");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("physiocare_backend.Models.EspecialidadTerapeuta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("EspecialidadesTerapeutas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Fisioterapia Deportiva"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Fisioterapia Geriátrica"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Fisioterapia Cardiovascular"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.EstadoCita", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("EstadosCitas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Programada"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Confirmada"
                        },
                        new
                        {
                            id = 3,
                            nombre = "En Curso"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Completada"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.EstadoCivil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id");

                    b.ToTable("EstadosCiviles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Soltero(a)"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Casado(a)"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Unión Libre"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Divorciado(a)"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Viudo(a)"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Masculino"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Femenino"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Otro"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoSangreId")
                        .HasColumnType("int");

                    b.Property<string>("correoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("numeroDocumento")
                        .HasColumnType("bigint");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resumenClinico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("telefono")
                        .HasColumnType("bigint");

                    b.Property<long?>("telefonoEmergencia")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoSangreId");

                    b.HasIndex("numeroDocumento")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("physiocare_backend.Models.ServicioTerapia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CategoriaTerapiaId")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("nombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("CategoriaTerapiaId");

                    b.ToTable("Terapias");
                });

            modelBuilder.Entity("physiocare_backend.Models.Terapeuta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("EspecialidadTerapeutaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("correoLaboral")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diasLaborales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("horaFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("horaInicio")
                        .HasColumnType("time");

                    b.Property<long>("numeroDocumento")
                        .HasColumnType("bigint");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tarjetaProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("telefonoContacto")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("EspecialidadTerapeutaId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("numeroDocumento")
                        .IsUnique();

                    b.ToTable("Terapeutas");
                });

            modelBuilder.Entity("physiocare_backend.Models.TipoDocumento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id");

                    b.ToTable("TiposDocumento");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Tarjeta de Identidad"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Cédula de Extranjería"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Pasaporte"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.TipoSangre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("id");

                    b.ToTable("TiposSangre");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "O+"
                        },
                        new
                        {
                            id = 2,
                            nombre = "O-"
                        },
                        new
                        {
                            id = 3,
                            nombre = "A+"
                        },
                        new
                        {
                            id = 4,
                            nombre = "A-"
                        },
                        new
                        {
                            id = 5,
                            nombre = "B+"
                        },
                        new
                        {
                            id = 6,
                            nombre = "B-"
                        },
                        new
                        {
                            id = 7,
                            nombre = "AB+"
                        },
                        new
                        {
                            id = 8,
                            nombre = "AB-"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            passwordHash = "$2a$12$ZpYbeSWhvLg7l6Z5GskqXOnlPCOvF80ZJc9bVvF0XN6h3u6bBfTpq",
                            username = "Admin"
                        });
                });

            modelBuilder.Entity("physiocare_backend.Models.CategoriaTerapia", b =>
                {
                    b.HasOne("physiocare_backend.Models.EspecialidadTerapeuta", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("physiocare_backend.Models.Cita", b =>
                {
                    b.HasOne("physiocare_backend.Models.EstadoCita", "EstadoCita")
                        .WithMany()
                        .HasForeignKey("EstadoCitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.ServicioTerapia", "ServicioTerapia")
                        .WithMany()
                        .HasForeignKey("ServicioTerapiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.Terapeuta", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCita");

                    b.Navigation("Paciente");

                    b.Navigation("ServicioTerapia");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("physiocare_backend.Models.Paciente", b =>
                {
                    b.HasOne("physiocare_backend.Models.EstadoCivil", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.TipoSangre", "TipoSangre")
                        .WithMany()
                        .HasForeignKey("TipoSangreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCivil");

                    b.Navigation("Genero");

                    b.Navigation("TipoDocumento");

                    b.Navigation("TipoSangre");
                });

            modelBuilder.Entity("physiocare_backend.Models.ServicioTerapia", b =>
                {
                    b.HasOne("physiocare_backend.Models.CategoriaTerapia", "CategoriaTerapia")
                        .WithMany()
                        .HasForeignKey("CategoriaTerapiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaTerapia");
                });

            modelBuilder.Entity("physiocare_backend.Models.Terapeuta", b =>
                {
                    b.HasOne("physiocare_backend.Models.EspecialidadTerapeuta", "EspecialidadTerapeuta")
                        .WithMany()
                        .HasForeignKey("EspecialidadTerapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("physiocare_backend.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EspecialidadTerapeuta");

                    b.Navigation("TipoDocumento");
                });
#pragma warning restore 612, 618
        }
    }
}
